### ISSUE TITLE
Shelf privacy is not persisted

### ISSUE THREAD

**Issue by killpack** [mouse-reeve/bookwyrm#511] opened 2021-01-11 20:28 UTC
**Describe the bug**
The "Shelf privacy" form on the "Your Shelves" page doesn't seem to do anything.

**To Reproduce**
1. Go to "Your Shelves" ( /user/.../shelves )
2. Click the pencil icon next to any shelf (eg. "To Read")
3. Change the "Shelf privacy" dropdown to any value other than "Public" (eg. "Unlisted") and click "Update shelf"
4. Click the pencil icon once again and notice that it still says "Public"

**Expected behavior**
The shelf privacy value should be persisted to whatever other value was selected (eg. "Unlisted").

**Screenshots**
Here's the dropdown in question-
<img width="395" alt="Screen Shot 2021-01-11 at 3 19 11 PM" src="https://user-images.githubusercontent.com/3970187/104233902-a5a9fe00-5420-11eb-8d4d-216494240079.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 84

**Additional context**
Apologies if this is a known issue, or if the privacy levels are WIP- I took a look through existing issues and the project tracking page, but I didn't see anything that seemed related.

**Comment by killpack** [comment] 2021-01-11 20:30
Actually, maybe this is a duplicate of https://github.com/mouse-reeve/bookwyrm/issues/258?

**Comment by mouse-reeve** [comment] 2021-01-11 22:45
definitely a bug! not quite a dupe of 258, but sorta related. thanks for reporting <3

**Closed** 2021-01-11 23:28 UTC
