### ISSUE TITLE
Adding a tag to a review reloads the view and deletes the review's text and title

### ISSUE THREAD

**Issue by jan-webdev** [mouse-reeve/bookwyrm#659] opened 2021-02-28 15:20 UTC
_I hope this hasn't been reported before but I couldn't find a similar issue._

**Describe the bug**
When I write a new review for a book and come to the last section before saving, the tag section, adding a new tag reloads the page (at least in Firefox under Win10). While the tag is being added, the title and review text are gone :(

**To Reproduce**
1. Go to a single book's view (eg: https://bookwyrm.social/book/12345)
2. Fill out the review title and text
3. Scroll down to "Tags" and add in a tag
4. The page reloads and loses the review/title text

**Expected behavior**
I expect the tags to be added but the page not to be refreshed AND the text not to be lost.
(Might be a different topic but I would also expect to be able to add a bunch of tags, separated by commas, at once. But when I do that it will be added as one long word. This might need to be clarified.)

**Desktop (please complete the following information):**
 - OS: Win 10 64
 - Browser: Firefox

**Comment by mouse-reeve** [comment] 2021-03-05 01:29
this is a duplicate of #475 and a good reminder to me to get around to fixing this sooner rather than later

**Closed by mouse-reeve** 2021-03-05 01:29 UTC
