### ISSUE TITLE
UndefinedTable: relation "bookwyrm_userrelationship" does not exist error

### ISSUE THREAD

**Issue by ibrand** [mouse-reeve/bookwyrm#353] opened 2020-11-19 00:01 UTC
**Describe the bug**
I went to go load up the development env today after a little while of not using it and came across this error when I ran the `docker-compose run --rm web python manage.py migrate` cmd to keep up with new migrations:

```
docker-compose run --rm web python manage.py migrate
Creating bookwyrm_web_run ... done
Operations to perform:
  Apply all migrations: admin, auth, bookwyrm, contenttypes, sessions
Running migrations:
  Applying bookwyrm.0006_auto_20200221_1702_squashed_0064_merge_20201101_1913...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "bookwyrm_userrelationship" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 822, in database_forwards
    schema_editor.add_constraint(model, self.constraint)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 362, in add_constraint
    self.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "bookwyrm_userrelationship" does not exist
```

**To Reproduce**
Run the `docker-compose run --rm web python manage.py migrate` command

**Expected behavior**
Migrations should run

**Desktop (please complete the following information):**
 - OS: Mac OS
- Latest git pull

**Additional context**
I saw a commit with the msg "migrations are fucked" and I'm guessing you've experienced part of this problem before. Happy to provide any other context or try anything out here!

**Comment by mouse-reeve** [comment] 2020-11-19 00:15
dang that squash migrations was supposed to FIX this problem. if you reset the database and start over it should work, but "delete all your data" is, I suppose, not necessarily a great solution. What migration were you on when you tried to run the latest?

**Comment by cincodenada** [comment] 2020-11-19 03:41
I just updated a Bookwyrm instance I initially set up in July, and after a little wrestling with migrations (my database still had `fedireads_` prefixed tables) I decided it'd be easier to just set up a new instance and then manually migrate the little data I had over in the messiest way possible, by manually merging a database dump of the new and the old.

I'm not sure if it was actually easier than figuring out how to make migrations work - I think if your tables are old enough that they're named `fedireads` then migrations alone won't work, because unless I'm missing something there's no migration to do that rename. Since the migrations are namespaced it might be possible to create such a migration though? I'm not familiar with Django's migrations specifically.

**Comment by cincodenada** [comment] 2020-11-19 04:46
I got it in my brain to take another run at this and did a trial of migrating from a pre-rename database and found [this Django command](https://odwyer.software/blog/how-to-rename-an-existing-django-application) which seemed to work a charm. I'm happy to look at putting up a PR to integrate it into the existing migration flow it that's helpful, but I'm not sure how solved this problem is already :)

**Comment by mouse-reeve** [comment] 2020-11-19 05:02
oh that's interesting, I didn't think about the name change causing issues for migrations because I reset my local database pretty often in development

**Comment by mouse-reeve** [comment] 2020-11-19 05:07
I just remembered that when I ran this migration on the production database, I ran `docker-compose exec web python manage.py migrate bookwyrm 0006 --fake` to tick the version number correctly before running the subsequent migrations. It was fully up to date on all the migrations prior to the squash when I did that though

**Comment by ibrand** [comment] 2020-11-19 19:55
So I unfortunately don't remember which migration I was on when I first ran it because I ended up actually deleting the repo and re-cloning since I barely had any data in the test DB and had a feeling that something got a little messed up between migrations. That said, when I went back through the docker set up on a fresh pull of the repo I still saw this same error.

I wonder if even on a clean install a command like `docker-compose exec web python manage.py migrate bookwyrm 0006 --fake` is needed? I'm pretty new to the Django ecosystem, but if it needs to run 1 migration after the next even on a fresh DB then I'm guessing that same strategy would be needed

**Comment by cincodenada** [comment] 2020-11-19 20:56
Hmm, so the database is managed by Docker and isn't stored in the repo, so I don't think deleting and re-cloning your repo by itself will reset the database as long as you cloned it back into the same directory.

Can you run `docker container ls` to see what containers you have currently? If my guess is correct you'll have a db image that was created some time ago.

**Comment by ibrand** [comment] 2020-11-19 21:06
Oh I didn't realize that about Docker but it makes lots of sense that it works that way. Yep it's a 4 week old DB. So I suppose I could destroy the docker DB and rebuild from there, or we could leverage this set up to try and dig a little deeper into the migration problem

**Comment by cincodenada** [comment] 2020-11-19 22:07
Okay, cool, thanks for looking into that. In that case, I'm guessing your database still has tables prefixed with `fedireads`, and they need to be renamed before the migrations can continue. Fortunately I found a command that promises to do just that that seemed to work in my testing.

I just put up PR #355 which, if it works like I hope, would make the migration command "just work" for this situation. Can you want try pulling it down (or just manually applying the changes, there's not much to it cause the new command is doing all the work) and re-running migrations through the `fr-dev` script (`./fr-dev migrate`)? Worst case it'll just fail again in the same way, so shouldn't be much to lose.

**Comment by ibrand** [comment] 2020-11-20 18:24
Thanks for jumping into this @cincodenada 😄 I think I ran into the "fedireads prefix" problem when I was first setting up and addressed it. I see:
```
fedireads=# \dt
                      List of relations
 Schema |              Name              | Type  |   Owner
--------+--------------------------------+-------+-----------
 public | auth_group                     | table | fedireads
 public | auth_group_permissions         | table | fedireads
 public | auth_permission                | table | fedireads
 public | bookwyrm_author                | table | fedireads
 public | bookwyrm_book                  | table | fedireads
 public | bookwyrm_book_authors          | table | fedireads
 public | bookwyrm_boost                 | table | fedireads
 public | bookwyrm_comment               | table | fedireads
 public | bookwyrm_connector             | table | fedireads
 public | bookwyrm_edition               | table | fedireads
 public | bookwyrm_favorite              | table | fedireads
 public | bookwyrm_federatedserver       | table | fedireads
 public | bookwyrm_generatedstatus       | table | fedireads
 public | bookwyrm_importitem            | table | fedireads
 public | bookwyrm_importjob             | table | fedireads
 public | bookwyrm_notification          | table | fedireads
 public | bookwyrm_passwordreset         | table | fedireads
 public | bookwyrm_quotation             | table | fedireads
 public | bookwyrm_readthrough           | table | fedireads
 public | bookwyrm_review                | table | fedireads
 public | bookwyrm_shelf                 | table | fedireads
 public | bookwyrm_shelfbook             | table | fedireads
 public | bookwyrm_siteinvite            | table | fedireads
 public | bookwyrm_sitesettings          | table | fedireads
 public | bookwyrm_status                | table | fedireads
 public | bookwyrm_status_mention_books  | table | fedireads
 public | bookwyrm_status_mention_users  | table | fedireads
 public | bookwyrm_tag                   | table | fedireads
 public | bookwyrm_user                  | table | fedireads
 public | bookwyrm_user_groups           | table | fedireads
 public | bookwyrm_user_user_permissions | table | fedireads
 public | bookwyrm_userblocks            | table | fedireads
 public | bookwyrm_userfollowrequest     | table | fedireads
 public | bookwyrm_userfollows           | table | fedireads
 public | bookwyrm_work                  | table | fedireads
 public | django_admin_log               | table | fedireads
 public | django_content_type            | table | fedireads
 public | django_migrations              | table | fedireads
 public | django_session                 | table | fedireads
(39 rows)
```

I wonder if the fact that `owner` is `fedireads` is a problem? Does this look how you'd expect it to look?

I do notice that there's still no table called `bookwyrm_userrelationship` which is where that error comes into the picture. I wonder if the squashed migration doesn't add that table? Happy to dig into the migrations folder a bit for that.

**Comment by cincodenada** [comment] 2020-11-21 01:17
Huh, okay yeah that's how I'd expect it to look, so the rename won't help you. The `fedireads` owner shouldn't be a problem, and the fact that the migrations can tell that `bookwyrm_userrelationship` doesn't exist demonstrate that it's able to access the database just fine.

It looks like `userrelationship` should be in the initial migration, so it's strange that it's not there. What do you get if you do `SELECT * FROM django_migrations;` in `./fr-dev dbshell` - that'll tell us what migrations have run so far.

**Comment by cincodenada** [comment] 2020-11-21 01:52
Okay, so no need to poke around yourself, I was able to reproduce this myself by checking out a version from 4 weeks ago, setting things up, and then pulling the latest changes and trying to migrate. Seeing if I can get clever and fix things, from here, I'll let you know what I find!

**Comment by cincodenada** [comment] 2020-11-21 02:40
Okay, so the problem is that `0006_auto_20200221_1702_squashed_0064_merge_20201101_1913` migration is a big ol' combination of what was previously migrations 0006-0064, so anyone who initialized things before that needs to do some resetting of things. You're probably around migration 50 or some such.

I made a little helper script to do the resetting, would you mind testing it out on your setup? It worked as expected on my reproduced version. You can download this script, put it in the base directory of your repo, and and run it with `bash fix_migrations.sh` - it should go through all the steps to roll back the repo, apply the old migrations, and then get you up to speed with the current ones.

It will try to stash and restore any changes you have, but I'd start with a clean repo anyway.

**Comment by cincodenada** [comment] 2020-11-21 05:51
Gah, Github got all fancy and because I said I _thought_ #355 would fix this, it went ahead and closed this issue when that was merged. It did not fix it, this should be re-opened :)

**Comment by ibrand** [comment] 2020-11-21 21:39
Nice script! Ok so here's what happened:
I ran the script, and then went ahead with `docker compose up` and saw some errors so I reran `docker compose build`, after doing that I could successfully run `docker compose up` see localhost:8000 and I tried to log in. I'm unsure if I actually entered the right credentials, but regardless I get a lot of these (along with the Django browser error):

```
db_1             | 2020-11-21 21:33:54.825 UTC [36] ERROR:  column bookwyrm_shelf.privacy does not exist at character 240
db_1             | 2020-11-21 21:33:54.825 UTC [36] STATEMENT:  SELECT "bookwyrm_shelf"."id", "bookwyrm_shelf"."created_date", "bookwyrm_shelf"."updated_date", "bookwyrm_shelf"."remote_id", "bookwyrm_shelf"."name", "bookwyrm_shelf"."identifier", "bookwyrm_shelf"."user_id", "bookwyrm_shelf"."editable", "bookwyrm_shelf"."privacy" FROM "bookwyrm_shelf" WHERE ("bookwyrm_shelf"."user_id" = 1 AND "bookwyrm_shelf"."identifier" = 'reading') LIMIT 21
web_1            | Internal Server Error: /
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
web_1            |     return self.cursor.execute(sql, params)
web_1            | psycopg2.errors.UndefinedColumn: column bookwyrm_shelf.privacy does not exist
web_1            | LINE 1: ...rm_shelf"."user_id", "bookwyrm_shelf"."editable", "bookwyrm_...
```

This leads me to believe that there's some other migration somewhere that wasn't run? To investigate, I went back into the postgres DB and ran `\dt`. I noticed that I still don't see `bookwyrm_userrelationship` but I *do* seem to have `bookwyrm_shelf`

For what it's worth, there's almost nothing in the DB so if I had to delete it that wouldn't be a bad outcome, but I know that part of the point here is to understand what to do about backwards compatibility

**Comment by cincodenada** [comment] 2020-11-21 22:44
Hmm, it does seem like there are some migrations missing. Can you go into a dbshell again and run `SELECT * FROM django_migrations;` to see what migrations we've managed to run so far?

And thanks for the note - I appreciate your helping troubleshoot for future folks!

**Comment by ibrand** [comment] 2020-11-24 18:14
<details>
<summary>The output is pretty long so I made it collapsible, but here's the whole output of <code>SELECT * FROM django_migrations;</code></summary>

```
fedireads=# SELECT * FROM django_migrations;
 id |     app      |                   name                   |            applied
----+--------------+------------------------------------------+-------------------------------
  1 | contenttypes | 0001_initial                             | 2020-10-20 15:33:10.564181+00
  2 | contenttypes | 0002_remove_content_type_name            | 2020-10-20 15:33:10.573272+00
  3 | auth         | 0001_initial                             | 2020-10-20 15:33:10.593579+00
  4 | auth         | 0002_alter_permission_name_max_length    | 2020-10-20 15:33:10.611129+00
  5 | auth         | 0003_alter_user_email_max_length         | 2020-10-20 15:33:10.617511+00
  6 | auth         | 0004_alter_user_username_opts            | 2020-10-20 15:33:10.624666+00
  7 | auth         | 0005_alter_user_last_login_null          | 2020-10-20 15:33:10.63123+00
  8 | auth         | 0006_require_contenttypes_0002           | 2020-10-20 15:33:10.633539+00
  9 | auth         | 0007_alter_validators_add_error_messages | 2020-10-20 15:33:10.640619+00
 10 | auth         | 0008_alter_user_username_max_length      | 2020-10-20 15:33:10.647106+00
 11 | auth         | 0009_alter_user_last_name_max_length     | 2020-10-20 15:33:10.653216+00
 12 | auth         | 0010_alter_group_name_max_length         | 2020-10-20 15:33:10.659778+00
 13 | auth         | 0011_update_proxy_permissions            | 2020-10-20 15:33:10.667203+00
 14 | bookwyrm     | 0001_initial                             | 2020-10-20 15:33:10.861613+00
 15 | admin        | 0001_initial                             | 2020-10-20 15:33:10.941147+00
 16 | admin        | 0002_logentry_remove_auto_add            | 2020-10-20 15:33:10.962707+00
 17 | admin        | 0003_logentry_add_action_flag_choices    | 2020-10-20 15:33:11.008129+00
 18 | bookwyrm     | 0002_auto_20200219_0816                  | 2020-10-20 15:33:11.066434+00
 19 | bookwyrm     | 0003_auto_20200221_0131                  | 2020-10-20 15:33:11.274898+00
 20 | bookwyrm     | 0004_tag                                 | 2020-10-20 15:33:11.29672+00
 21 | bookwyrm     | 0005_auto_20200221_1645                  | 2020-10-20 15:33:11.358332+00
 22 | bookwyrm     | 0006_auto_20200221_1702                  | 2020-10-20 15:33:11.376771+00
 23 | bookwyrm     | 0007_auto_20200223_0902                  | 2020-10-20 15:33:11.395476+00
 24 | bookwyrm     | 0008_auto_20200224_1504                  | 2020-10-20 15:33:11.414685+00
 25 | bookwyrm     | 0009_status_published_date               | 2020-10-20 15:33:11.434784+00
 26 | bookwyrm     | 0010_auto_20200307_0655                  | 2020-10-20 15:33:11.792919+00
 27 | bookwyrm     | 0011_notification                        | 2020-10-20 15:33:11.830095+00
 28 | bookwyrm     | 0012_auto_20200308_1625                  | 2020-10-20 15:33:11.845658+00
 29 | bookwyrm     | 0013_user_manually_approves_followers    | 2020-10-20 15:33:11.865206+00
 30 | bookwyrm     | 0014_status_remote_id                    | 2020-10-20 15:33:11.888335+00
 31 | bookwyrm     | 0015_auto_20200311_1212                  | 2020-10-20 15:33:12.196973+00
 32 | bookwyrm     | 0016_auto_20200313_1337                  | 2020-10-20 15:33:12.25042+00
 33 | bookwyrm     | 0017_auto_20200314_2152                  | 2020-10-20 15:33:12.302439+00
 34 | bookwyrm     | 0018_favorite_remote_id                  | 2020-10-20 15:33:12.326459+00
 35 | bookwyrm     | 0019_comment                             | 2020-10-20 15:33:12.353828+00
 36 | bookwyrm     | 0020_auto_20200327_2335                  | 2020-10-20 15:33:12.449969+00
 37 | bookwyrm     | 0021_auto_20200328_0428                  | 2020-10-20 15:33:12.541113+00
 38 | bookwyrm     | 0022_auto_20200328_2001                  | 2020-10-20 15:33:12.561987+00
 39 | bookwyrm     | 0023_auto_20200328_2203                  | 2020-10-20 15:33:12.914071+00
 40 | bookwyrm     | 0024_federatedserver_application_version | 2020-10-20 15:33:12.924503+00
 41 | bookwyrm     | 0025_auto_20200330_0037                  | 2020-10-20 15:33:12.969695+00
 42 | bookwyrm     | 0026_auto_20200330_1456                  | 2020-10-20 15:33:13.084819+00
 43 | bookwyrm     | 0027_auto_20200330_2232                  | 2020-10-20 15:33:13.477828+00
 44 | bookwyrm     | 0028_auto_20200401_1824                  | 2020-10-20 15:33:13.521505+00
 45 | bookwyrm     | 0029_auto_20200403_1835                  | 2020-10-20 15:33:13.544861+00
 46 | bookwyrm     | 0030_quotation                           | 2020-10-20 15:33:13.57499+00
 47 | bookwyrm     | 0031_readthrough                         | 2020-10-20 15:33:13.609177+00
 48 | bookwyrm     | 0032_auto_20200421_1347                  | 2020-10-20 15:33:13.767507+00
 49 | bookwyrm     | 0033_auto_20200422_1249                  | 2020-10-20 15:33:13.906149+00
 50 | bookwyrm     | 0034_importjob_import_status             | 2020-10-20 15:33:13.996916+00
 51 | bookwyrm     | 0035_auto_20200429_1708                  | 2020-10-20 15:33:14.069936+00
 52 | bookwyrm     | 0036_auto_20200503_2007                  | 2020-10-20 15:33:14.103049+00
 53 | bookwyrm     | 0037_auto_20200504_0154                  | 2020-10-20 15:33:14.146654+00
 54 | bookwyrm     | 0038_author_remote_id                    | 2020-10-20 15:33:14.155336+00
 55 | bookwyrm     | 0039_auto_20200510_2342                  | 2020-10-20 15:33:14.170604+00
 56 | bookwyrm     | 0040_auto_20200513_0153                  | 2020-10-20 15:33:14.42394+00
 57 | bookwyrm     | 0041_user_remote_id                      | 2020-10-20 15:33:14.449429+00
 58 | bookwyrm     | 0042_sitesettings                        | 2020-10-20 15:33:14.459055+00
 59 | bookwyrm     | 0043_siteinvite                          | 2020-10-20 15:33:14.466383+00
 60 | bookwyrm     | 0044_siteinvite_user                     | 2020-10-20 15:33:14.500719+00
 61 | bookwyrm     | 0042_auto_20200524_0346                  | 2020-10-20 15:33:14.608528+00
 62 | bookwyrm     | 0045_merge_20200810_2010                 | 2020-10-20 15:33:14.611546+00
 63 | bookwyrm     | 0046_auto_20200921_1509                  | 2020-10-20 15:33:14.653073+00
 64 | bookwyrm     | 0047_auto_20200928_2312                  | 2020-10-20 15:33:14.662146+00
 65 | bookwyrm     | 0048_generatednote                       | 2020-10-20 15:33:14.696552+00
 66 | bookwyrm     | 0049_passwordreset                       | 2020-10-20 15:33:14.73184+00
 67 | bookwyrm     | 0050_auto_20201002_2156                  | 2020-10-20 15:33:14.762783+00
 68 | bookwyrm     | 0051_auto_20201005_2142                  | 2020-10-20 15:33:14.768214+00
 69 | bookwyrm     | 0052_auto_20201005_2145                  | 2020-10-20 15:33:14.798147+00
 70 | bookwyrm     | 0053_auto_20201006_2020                  | 2020-10-20 15:33:14.85617+00
 71 | bookwyrm     | 0054_auto_20201016_2359                  | 2020-10-20 15:33:14.88641+00
 72 | bookwyrm     | 0053_auto_20201014_1700                  | 2020-10-20 15:33:14.901067+00
 73 | bookwyrm     | 0054_auto_20201016_1707                  | 2020-10-20 15:33:14.965931+00
 74 | bookwyrm     | 0055_merge_20201017_0011                 | 2020-10-20 15:33:14.968509+00
 75 | sessions     | 0001_initial                             | 2020-10-20 15:33:14.975912+00
 76 | bookwyrm     | 0056_auto_20201021_0150                  | 2020-10-22 17:19:12.735632+00
 77 | bookwyrm     | 0057_auto_20201026_2131                  | 2020-11-21 21:18:32.232188+00
 78 | bookwyrm     | 0058_remove_importjob_import_status      | 2020-11-21 21:18:32.337436+00
 79 | bookwyrm     | 0059_auto_20201030_1755                  | 2020-11-21 21:18:32.412506+00
 80 | bookwyrm     | 0060_auto_20201030_2010                  | 2020-11-21 21:18:32.489793+00
 81 | bookwyrm     | 0061_auto_20201030_2157                  | 2020-11-21 21:18:32.643305+00
 82 | bookwyrm     | 0062_auto_20201031_1936                  | 2020-11-21 21:18:32.685252+00
 83 | bookwyrm     | 0063_user_last_active_date               | 2020-11-21 21:18:32.713755+00
 84 | bookwyrm     | 0063_auto_20201101_1758                  | 2020-11-21 21:18:32.812087+00
 85 | bookwyrm     | 0064_merge_20201101_1913                 | 2020-11-21 21:18:32.815384+00
(85 rows)
```
</details>

I scanned the list for flags for what might be happening. I first looked for any numbers that might be skipped in the index -- like does it go from 0060 to 0062 or something. I didn't see any of that, but I did see this:
```
 83 | bookwyrm     | 0063_user_last_active_date               | 2020-11-21 21:18:32.713755+00
 84 | bookwyrm     | 0063_auto_20201101_1758                  | 2020-11-21 21:18:32.812087+00
```
And I see that there are 2 0063's. I wonder if the migrations are getting tripped up there?

**Comment by mouse-reeve** [comment] 2020-11-24 19:33
the 0064 merge migration ought to resolve the two 0063 migrations, but it does seem fishy that the last migration before everything got screwed up was a merge migration

**Comment by ibrand** [comment] 2020-11-24 20:27
Ah here's something helpful. I ran `docker-compose run --rm web python manage.py showmigrations` and see:
```
bookwyrm
 [X] 0001_initial
 [X] 0002_auto_20200219_0816
 [X] 0003_auto_20200221_0131
 [X] 0004_tag
 [X] 0005_auto_20200221_1645
 [ ] 0006_auto_20200221_1702_squashed_0064_merge_20201101_1913
 [ ] 0007_auto_20201103_0014
 [ ] 0008_work_default_edition
 [ ] 0009_shelf_privacy
 [ ] 0010_importjob_retry
 [ ] 0011_auto_20201113_1727
```
So it does look like some of the old migrations weren't run (from the squash on.) When I try to run only the squashed migration -- `docker-compose run web python manage.py migrate bookwyrm 0006_auto_20200221_1702_squashed_0064_merge_20201101_1913` -- I see the original error:
```
Operations to perform:
  Target specific migration: 0006_auto_20200221_1702_squashed_0064_merge_20201101_1913, from bookwyrm
Running migrations:
  Applying bookwyrm.0006_auto_20200221_1702_squashed_0064_merge_20201101_1913...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "bookwyrm_userrelationship" does not exist
```

I think the next step would be to look inside of the squashed migration and see what's going on there

**Comment by cincodenada** [comment] 2020-11-24 20:50
Okay, so that's all very helpful, thanks. The squashed migration is basically the "old" migrations 0006-0064 all rolled into one, so it won't work if you already ran the old migrations (which you were partway through before all this).

So I think what needs to happen is to run the following, which is in the script but maybe didn't work right for some reason on your setup:
```
docker-compose exec web python manage.py migrate bookwyrm 0006 --fake
```
What this does is, as the `--fake` implies, adds a little lie to the migrations log - it says "don't actually run this migration, but say that you did, I promise I made the database look like it should". Which is what we want, because you _have_ run everything that's in `0006_auto_20200221_1702_squashed_0064_merge_20201101_1913`, but you ran them under the old names so the current migrations don't know how to map them.

Running that `--fake` command should check the `0006` box in `showmigrations`, and from there you should be able to run `./fr-dev migrate` as usual to get up to date.

And a sidenote on the 0063 thing, my understanding aligns with @mouse-reeve - the numbers I think are mostly for human convenience, because inside each migration there's a dependencies list of which other migrations should run before it, and Django looks through and puts things in order based on that. It also complains if there's more than one "latest" migration, so 0064 is a placeholder to say "okay I'm the last one, and I need both 0063's first". And it does look like it ran successfully on your setup, so you should have all the changes that are rolled into the squashed migration and be good to go from there.

**Comment by ibrand** [comment] 2020-11-24 21:13
That worked 🥳 ! That clears a lot up since I had seen "merge" and thought that 006 was a merge of just 2 migrations and didn't realize it was a merge and squash of the whole history up until then. Sounds like the right guidance if anyone else gets stuck on this is to run `docker-compose exec web python manage.py migrate bookwyrm 0006 --fake` and then rerun the migration and that should work

**Comment by cincodenada** [comment] 2020-11-24 21:27
Hurrah! :tada: Thanks for your patience and degbugging help!

And yes, `--fake` is an important part of the fix, but with a caveat: if (as in your case) you were somewhere in the middle of the squashed migrations (say, you were on 0050), you still have to run the rest of what's in the squashed migrations (0051-0064) - that's what the script did, rolled the repo back to before the squash, caught up to 0064, and then brought you back.

If you just run the `--fake` without having run all the way up to the old 0064, it'll let you, but then you'll be missing parts of the squashed migration and run into problems, either immediately or down the road. Django doesn't (and can't) verify that the database is actually in the state it expects it to be after the squashed commit, so we have to be careful to make sure that it is!

**Comment by mouse-reeve** [comment] 2020-11-24 21:39
thank you both for working through this!

**Closed** 2020-12-07 19:02 UTC
