### ISSUE TITLE
OpenLibrary updates are not reflected via search if a book is already imported

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#685] opened 2021-03-04 13:14 UTC
I've added a book to OpenLibrary, without filling in the author field by mistake. Then, I imported this book to Bookwyrm, thinking that I will be able to edit the author, unfortunately this is not possible at the moment.

I've modified the book, adding a new author on OpenLibrary.

When I search now via Bookwyrm, the book is still returned as having no author.

I thought that the book takes some time to refresh via the API, so I waited for about 12+ hours, and no change so far.

Is an OpenLibrary book cached on Bookwyrm's end, if so, is there a way to re-fetch when searching?

**Comment by mouse-reeve** [comment] 2021-03-04 15:39
yeah, this is a needed feature! I'm going to close this issue as a duplicate of #591

**Closed by mouse-reeve** 2021-03-04 15:39 UTC

**Comment by Flameborn** [comment] 2021-03-04 15:42
Ah, makes sense. I wasn't sure if this was a generic issue or just something regarding OpenLibrary only.
